; base de teste
[ts]
;local = '179.188.44.26';
;usuario = 'ligmototaxi';
;senha = 'ligmlm01';
;banco = 'ligmototaxi';

;
;local = '179.188.16.25';
;usuario = 'ligmototaxiuser';
;senha = 'ligmlm01';
;banco = 'ligmototaxi';

local = 'db-internal.appmapp.com.br';
usuario = 'mototaxionlineus';
senha = 'mototaximlm01';
banco = 'devmappsistemas';


;base do google
;local = '35.199.121.116';
;usuario = 'ligmototaxiuser';
;senha = 'ligmlm01';
;banco = 'ligmototaxi';

;base do google
;local = '35.199.121.116';
;usuario = 'mototaxionlineus';
;senha = 'mototaximlm01';
;banco = 'testeMap';
 

;local = '35.199.121.116';
;usuario = 'mototaxionlineus';
;senha = 'mototaximlm01';
;banco = 'devmappsistemas';



;usuario = 'ligmototaxiuser';
;senha = 'ligmlm01';
;banco = 'ligmototaxi';
;base do google
;local = '35.199.121.116';
;usuario = 'weslley';
;senha = 'weslley0102';
;banco = 'ligmototaxi';

;base do google
;local = '35.199.121.116';
;usuario = 'weslley';
;senha = 'weslley0102';
;banco = 'entregaspbcmapp';

;base do google
;local = '35.199.121.116';
;usuario = 'weslley';
;senha = 'weslley0102';
;banco = 'zipmarvlog';

;base do google
;local = '35.199.121.116';
;usuario = 'weslley';
;senha = 'weslley0102';
;banco = 'gospeed';



;
;base do google
;local = '35.199.121.116';
;usuario = 'weslley';
;senha = 'weslley0102';
;banco = 'mexsolog10';

;base do google
;local = '35.199.121.116';
;usuario = 'weslley';
;senha = 'weslley0102';
;banco = 'wimovebcmapp';





















